### ISSUE TITLE
Rancher Desktop

### ISSUE THREAD

**Issue by negaolucifer** [apache/openwhisk-wskdebug#119]
I'm using [Rancher Desktop](https://rancherdesktop.io/) on Windows 10 and it seems containers are not starting...

Is it possible to use it with rancher desktop?

**Comment by alexkli** [comment]
@negaolucifer I don't see how Rancher Desktop is related to [Apache Openwhisk](https://openwhisk.apache.org)? openwhisk-wskdebug is solely a debugging tool for the Openwhisk serverless framework.

**Comment by negaolucifer** [comment]
Aye, that's true. But it needs docker, and it worked with docker desktop, but it isn't working with rancher desktop.

After some testing, it seems containers are not starting. I can, however, interact with the rancher docker, as listContainers list my running containers.

I was only asking for some help or directions with the rancher issue.

Thanks for your time @alexkli !
