### ISSUE TITLE
Error: Unknown Error From API: self signed certificate

### ISSUE THREAD

**Issue by proteche** [apache/openwhisk-wskdebug#24]
I have local setup of openwhisk using Docker-Compose (make quick-start). I am not able to start with "wskdebug someAction" command it gives me "Error: Unknown Error From API: self signed certificate".
I am not sure but its look like there is need of flag like --i (insecure) which is present in wsk -i action invoke someAction.

**Note:** i am not able to invoke actions without --i flag with wsk but its work with --insecure flag.
And I also tried with openwhisk-standalone.jar its works fine because its fire localhost 3232 and not https://192.168.etc...
Thanks!!

**Comment by alexkli** [comment]
There is an older hidden option `--ignoreCerts` that _should_ still work:

```
wskdebug someAction --ignoreCerts
```

Let us know if it doesn't.

**Comment by proteche** [comment]
thanks for reply, its works beautifully now. As i have local setup and i have a lots of endpoints(functions). And running each node container for debugging single function is not efficient on my local machine. so is there any efficient way to do that, do  i need to write some script to automate the process,  any suggestion will be helpful.

**Comment by alexkli** [comment]
Do you need to always debug all functions? How granular are they?

In my experience, I only wskdebug the one or two actions that I am working on, and that works well since for performance reasons they are not very small.
