### ISSUE TITLE
[activation DB agent] add X-OW-EXTRA-LOGGING header

### ISSUE THREAD

**Issue by alexkli** [apache/openwhisk-wskdebug#49]
Adapt for an upcoming (optional) feature in Openwhisk, which would break the activation DB polling agent (which is lower prio, since the concurrent one is preferred, and if that's not supported, ngrok works better).

The idea of that OW feature is to improve scalability of the activation record system by not storing the activation records in the database anymore for _blocking & successful_ activations. This means that `wsk activations list` and `wsk activation get <id>` won’t return anything for these activations.

But it can be forced by setting a header when invoking the action:

```
X-OW-EXTRA-LOGGING: on
```

This would have to be set when invoking the helper functions ~~[`<name>_wskdebug_invoked`](https://github.com/apache/openwhisk-wskdebug/blob/master/agent/agent-activationdb.js#L50)~~ and [`<name>_wskdebug_completed `](https://github.com/apache/openwhisk-wskdebug/blob/fa5b0b48fa7e3bad922b94ee80e5ff6f70800ded/src/agentmgr.js#L403).

It might be tricky to add a custom header in `openwhisk().actions.invoke()`. But [looking at the code](https://github.com/apache/openwhisk-client-js/blob/9f19b2e763c849c0e40162197ff8691573632d15/lib/client.js#L160-L169) it _might_ be possible using

```
actions.invoke()({
    name: "action",
    params: result,
    blocking: true,
    headers: {
        "X-OW-EXTRA-LOGGING": "on"
    }
});
```

This might just be a side effect, not necessarily a supported way. And this might "clear" the default authorization header, in which case one would have to construct & set it here.

**Comment by tysonnorris** [comment]
Currently OW invoker does not pass on state of "X-OW-EXTRA-LOGGING" into action container - it would be possible, but will take changing some plumbing inside the invoker to pass this on.
Would it be possible instead to change the _wskdebug_invoked etc to be invoked blocking, and return the response instead of the activation id?

**Comment by alexkli** [comment]
There should be no need to pass them through in any form. The code invoking those helper actions would be fixed to always add the header. These invocations have to be recorded as the result is looked up (polled) from the activation db, that’s the whole purpose. (The client interested in these is not the one making the invocation).

Last but not least this mechanism is not the main one for wskdebug and I would be happy to remove it completely. It’s only there for folks who a) have no concurrent actions enabled in their openwhisk and b) don’t wan to use the optional, 3rd party ngrok service.

**Comment by tysonnorris** [comment]
I see - I thought you were trying to pass through the header. It should be possible to set the header using OW js lib after the latest npm is released with this change to prevent clobbering all headers when passing headers to set (it should only overwrite headers that are included in the options) https://github.com/apache/openwhisk-client-js/pull/209

**Comment by alexkli** [comment]
[Release 3.21.2](https://github.com/apache/openwhisk-client-js/releases/tag/3.21.2) of `openwhisk-client-js` allows custom headers, so this issue can move ahead.
