### ISSUE TITLE
nodejs mounted action runner should set the right current working directory

### ISSUE THREAD

**Issue by alexkli** [apache/openwhisk-wskdebug#79]
In case actions are mounted locally in the container, the source directory is `/code` not `/nodejsAction`. The current working directory is normally `/nodejsAction` and some code might rely on it to find other files, so it should be adjusted accordingly if it's `/code`.

**Comment by alexkli** [comment]
The fix is probably to simply change the dir to `/code` in both mount scripts at the start of their `main()` functions:

- here for mount-require.js: https://github.com/apache/openwhisk-wskdebug/blob/master/src/kinds/nodejs/mount-require.js#L39
- here for mount-plain.js: https://github.com/apache/openwhisk-wskdebug/blob/master/src/kinds/nodejs/mount-plain.js#L46

It would probably have to take the parent dir of the `sourcePath`, i.e. set the cwd to the dir of the source file being required:

```javascript
process.chdir(path.dirname(path));
```

Not sure if this will fully address https://github.com/adobe/aio-cli-plugin-app/issues/282 because it depends how the action.zip is packaged and how that might be different from the raw source structure that is mounted 1:1 in the wskdebug mounting case.

cc @shazron

**Comment by shazron** [comment]
PR https://github.com/apache/openwhisk-wskdebug/pull/85
